/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controller.Cita_MedicaController;
import controller.DoctorController;
import controller.MedicamentoController;
import controller.PacienteController;
import controller.TratamientoController;
import controller.Tratamiento_MedicamentoController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Afgord
 */
public class frmAtenderCita extends javax.swing.JPanel {

    private final frmPrincipal principal;
    private final int idCita;

    private final Cita_MedicaController citaCtrl = new Cita_MedicaController();
    private final PacienteController pacienteCtrl = new PacienteController();
    private final DoctorController doctorCtrl = new DoctorController();
    private final MedicamentoController medicamentoCtrl = new MedicamentoController();
    private final TratamientoController tratamientoCtrl = new TratamientoController();
    private final Tratamiento_MedicamentoController tmCtrl = new Tratamiento_MedicamentoController();

    private model.Cita_Medica cita;
    private model.Paciente paciente;
    private model.Doctor doctor;

    private javax.swing.table.DefaultTableModel medsModel;

    private static class ComboItem {

        final int id;
        final String text;

        ComboItem(int id, String text) {
            this.id = id;
            this.text = text;
        }

        @Override
        public String toString() {
            return text;
        }
    }

    public frmAtenderCita(frmPrincipal principal, int idCita) {
        this.principal = principal;
        this.idCita = idCita;
        initComponents();
        postInit();
        cargarDatosIniciales();
    }

    /**
     * Creates new form frmAtenderCita
     */
    public frmAtenderCita() {
        this.principal = null;
        this.idCita = -1;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHEADER = new javax.swing.JPanel();
        lblAtenderCita = new javax.swing.JLabel();
        pnlPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scrlPaneMotivo = new javax.swing.JScrollPane();
        txtMotivoConsulta = new javax.swing.JTextArea();
        scrlTratamiento = new javax.swing.JScrollPane();
        txtTratamiento = new javax.swing.JTextArea();
        pnlMedicamentos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbMedicamento = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        scrlMedicamento = new javax.swing.JScrollPane();
        txtIndicacionesMedicamentos = new javax.swing.JTextArea();
        pnlBotonAgregarMed = new javax.swing.JPanel();
        btnAgregarMedicamento = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        scrlListaMedicamentos = new javax.swing.JScrollPane();
        tblMedicamentos = new javax.swing.JTable();
        btnQuitarMedicamento = new javax.swing.JButton();
        pnlDuracionTratamiento = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDuracionTratamiento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnFinalizarConsulta = new javax.swing.JButton();

        lblAtenderCita.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAtenderCita.setText("ATENDER CONSULTA");

        javax.swing.GroupLayout pnlHEADERLayout = new javax.swing.GroupLayout(pnlHEADER);
        pnlHEADER.setLayout(pnlHEADERLayout);
        pnlHEADERLayout.setHorizontalGroup(
            pnlHEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHEADERLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAtenderCita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHEADERLayout.setVerticalGroup(
            pnlHEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHEADERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtenderCita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Información del paciente");

        jLabel2.setText("Nombre completo");

        jLabel3.setText("Edad");

        txtEdad.addActionListener(this::txtEdadActionPerformed);

        jLabel4.setText("Motivo de consulta:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Diagnóstico y Tratamiento");

        jLabel6.setText("Descripción detallada");

        javax.swing.GroupLayout pnlPacienteLayout = new javax.swing.GroupLayout(pnlPaciente);
        pnlPaciente.setLayout(pnlPacienteLayout);
        pnlPacienteLayout.setHorizontalGroup(
            pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPacienteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(pnlPacienteLayout.createSequentialGroup()
                        .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPacienteLayout.setVerticalGroup(
            pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        txtMotivoConsulta.setColumns(20);
        txtMotivoConsulta.setRows(5);
        scrlPaneMotivo.setViewportView(txtMotivoConsulta);

        txtTratamiento.setColumns(20);
        txtTratamiento.setRows(5);
        scrlTratamiento.setViewportView(txtTratamiento);

        jLabel7.setText("Seleccionar medicamento");

        cmbMedicamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMedicamento.addActionListener(this::cmbMedicamentoActionPerformed);

        jLabel8.setText("Indicaciones de uso");

        txtIndicacionesMedicamentos.setColumns(20);
        txtIndicacionesMedicamentos.setRows(5);
        scrlMedicamento.setViewportView(txtIndicacionesMedicamentos);

        btnAgregarMedicamento.setText("AGREGAR MEDICAMENTO");
        btnAgregarMedicamento.addActionListener(this::btnAgregarMedicamentoActionPerformed);

        jLabel9.setText("Medicamentos recetados");

        tblMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlListaMedicamentos.setViewportView(tblMedicamentos);

        btnQuitarMedicamento.setText("QUITAR MEDICAMENTO");
        btnQuitarMedicamento.addActionListener(this::btnQuitarMedicamentoActionPerformed);

        javax.swing.GroupLayout pnlBotonAgregarMedLayout = new javax.swing.GroupLayout(pnlBotonAgregarMed);
        pnlBotonAgregarMed.setLayout(pnlBotonAgregarMedLayout);
        pnlBotonAgregarMedLayout.setHorizontalGroup(
            pnlBotonAgregarMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlListaMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnlBotonAgregarMedLayout.createSequentialGroup()
                .addGroup(pnlBotonAgregarMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonAgregarMedLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBotonAgregarMedLayout.createSequentialGroup()
                        .addComponent(btnAgregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        pnlBotonAgregarMedLayout.setVerticalGroup(
            pnlBotonAgregarMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonAgregarMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonAgregarMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMedicamento)
                    .addComponent(btnQuitarMedicamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlListaMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMedicamentosLayout = new javax.swing.GroupLayout(pnlMedicamentos);
        pnlMedicamentos.setLayout(pnlMedicamentosLayout);
        pnlMedicamentosLayout.setHorizontalGroup(
            pnlMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentosLayout.createSequentialGroup()
                .addGroup(pnlMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMedicamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMedicamentosLayout.createSequentialGroup()
                                .addGroup(pnlMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(scrlMedicamento)
                    .addComponent(pnlBotonAgregarMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMedicamentosLayout.setVerticalGroup(
            pnlMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotonAgregarMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Duración del tratamiento");

        txtDuracionTratamiento.addActionListener(this::txtDuracionTratamientoActionPerformed);

        javax.swing.GroupLayout pnlDuracionTratamientoLayout = new javax.swing.GroupLayout(pnlDuracionTratamiento);
        pnlDuracionTratamiento.setLayout(pnlDuracionTratamientoLayout);
        pnlDuracionTratamientoLayout.setHorizontalGroup(
            pnlDuracionTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDuracionTratamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDuracionTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDuracionTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDuracionTratamientoLayout.setVerticalGroup(
            pnlDuracionTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDuracionTratamientoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDuracionTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnFinalizarConsulta.setText("FINALIZAR CONSULTA");
        btnFinalizarConsulta.addActionListener(this::btnFinalizarConsultaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarConsulta)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnFinalizarConsulta))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrlTratamiento)
                                    .addComponent(pnlDuracionTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(pnlPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrlPaneMotivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDuracionTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrlPaneMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void cmbMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicamentoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (principal != null) {
            principal.mostrarMenu();
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFinalizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarConsultaActionPerformed

        if (idCita <= 0) {
            return;
        }

        String descripcion = txtTratamiento.getText().trim();
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción del tratamiento/diagnóstico es obligatoria.");
            return;
        }

        int duracion;
        try {
            duracion = Integer.parseInt(txtDuracionTratamiento.getText().trim());
            if (duracion <= 0) {
                throw new NumberFormatException();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Duración inválida. Debe ser un número mayor a 0.");
            return;
        }

        int op = JOptionPane.showConfirmDialog(
                this,
                "¿Finalizar la consulta?\nEsto marcará la cita como 'completada'.",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );
        if (op != JOptionPane.YES_OPTION) {
            return;
        }
        
        System.out.println("ATENDER -> idCita=" + idCita);
        // 1) Finaliza consulta (SP)
        boolean ok = tratamientoCtrl.finalizarConsulta(idCita, descripcion, duracion);
        if (!ok) {
            JOptionPane.showMessageDialog(this, tratamientoCtrl.getUltimo_mensaje());
            return;
        }

        int idTratamiento = tratamientoCtrl.getUltimo_id_tratamiento();

        System.out.println("id_tratamiento creado: " + idTratamiento);

        if (idTratamiento <= 0) {
            JOptionPane.showMessageDialog(this, "No se obtuvo el ID del tratamiento.");
            return;
        }

        System.out.println("Cantidad de medicamentos en tabla: " + medsModel.getRowCount());

        System.out.println("ID TRATAMIENTO (OUT): " + idTratamiento);
        System.out.println("Filas medsModel: " + medsModel.getRowCount());

        // 2) Insertar medicamentos asociados (si hay)
        for (int i = 0; i < medsModel.getRowCount(); i++) {
            Object col0 = medsModel.getValueAt(i, 0);
            Object col1 = medsModel.getValueAt(i, 1);
            Object col2 = medsModel.getValueAt(i, 2);

            System.out.println("Fila " + i + " -> col0=" + col0 + " col1=" + col1 + " col2=" + col2);

            int idMedicamento = Integer.parseInt(col0.toString());
            String indicaciones = col2.toString();

            boolean okMedicamento = tmCtrl.agregarMedicamento(idTratamiento, idMedicamento, indicaciones);
            if (!okMedicamento) {
                System.out.println("FALLÓ insertar: " + tmCtrl.getUltimo_mensaje());
                JOptionPane.showMessageDialog(this, tmCtrl.getUltimo_mensaje());
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Consulta finalizada correctamente.");

        op = JOptionPane.showConfirmDialog(
                this,
                "¿Desea atender otra cita registrada?",
                "Continuar",
                JOptionPane.YES_NO_OPTION
        );

        if (principal != null) {
            if (op == JOptionPane.YES_OPTION) {
                principal.mostrarSeleccionarCita(); // abre el diálogo para elegir otra cita
            } else {
                principal.mostrarMenu();            // regresa al menú principal
            }
        }
    }//GEN-LAST:event_btnFinalizarConsultaActionPerformed

    private void txtDuracionTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionTratamientoActionPerformed

    private void btnAgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicamentoActionPerformed
        int idMedicamento = getSelectedMedicamentoId();
        if (idMedicamento <= 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un medicamento.");
            return;
        }

        String indic = txtIndicacionesMedicamentos.getText().trim();
        if (indic.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe indicaciones.");
            return;
        }

        // Evitar duplicados
        for (int i = 0; i < medsModel.getRowCount(); i++) {
            int existente = Integer.parseInt(medsModel.getValueAt(i, 0).toString());
            if (existente == idMedicamento) {
                JOptionPane.showMessageDialog(this, "Ese medicamento ya está agregado.");
                return;
            }
        }

        String nombre = cmbMedicamento.getSelectedItem().toString();
        medsModel.addRow(new Object[]{idMedicamento, nombre, indic});

        // limpiar indicaciones para el siguiente
        txtIndicacionesMedicamentos.setText("");
        cmbMedicamento.setSelectedIndex(-1);
    }//GEN-LAST:event_btnAgregarMedicamentoActionPerformed

    private void btnQuitarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarMedicamentoActionPerformed
        // TODO add your handling code here:
        int row = tblMedicamentos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un medicamento de la tabla.");
            return;
        }

        int op = JOptionPane.showConfirmDialog(
                this,
                "¿Quitar el medicamento seleccionado?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (op == JOptionPane.YES_OPTION) {
            medsModel.removeRow(row);
        }

    }//GEN-LAST:event_btnQuitarMedicamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicamento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarConsulta;
    private javax.swing.JButton btnQuitarMedicamento;
    private javax.swing.JComboBox cmbMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtenderCita;
    private javax.swing.JPanel pnlBotonAgregarMed;
    private javax.swing.JPanel pnlDuracionTratamiento;
    private javax.swing.JPanel pnlHEADER;
    private javax.swing.JPanel pnlMedicamentos;
    private javax.swing.JPanel pnlPaciente;
    private javax.swing.JScrollPane scrlListaMedicamentos;
    private javax.swing.JScrollPane scrlMedicamento;
    private javax.swing.JScrollPane scrlPaneMotivo;
    private javax.swing.JScrollPane scrlTratamiento;
    private javax.swing.JTable tblMedicamentos;
    private javax.swing.JTextField txtDuracionTratamiento;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextArea txtIndicacionesMedicamentos;
    private javax.swing.JTextArea txtMotivoConsulta;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextArea txtTratamiento;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        // Campos que NO deberían editarse
        txtNombrePaciente.setEditable(false);
        txtEdad.setEditable(false);
        txtMotivoConsulta.setEditable(false);

        // Tabla de medicamentos recetados (temporal)
        medsModel = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Medicamento", "Indicaciones"},
                0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tblMedicamentos.setModel(medsModel);
        tblMedicamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // Limpia combos “Item 1”
        cmbMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>());
    }

    private void cargarDatosIniciales() {

        if (idCita <= 0) {
            JOptionPane.showMessageDialog(this, "ID de cita inválido.");
            return;
        }

        // 1) Traer cita
        cita = citaCtrl.obtenerPorId(idCita);
        if (cita == null) {
            JOptionPane.showMessageDialog(this, "No se encontró la cita: " + idCita);
            return;
        }

        // (Opcional) Regla: solo atender si está "en curso"
        String estado = (cita.getEstado() == null) ? "" : cita.getEstado().trim().toLowerCase();
        if (!estado.equals("en curso")) {
            JOptionPane.showMessageDialog(this,
                    "Esta cita no está en curso.\nEstado actual: " + estado);
            // Si quieres obligar regresar:
            // if (principal != null) principal.mostrarMenu();
            // return;
        }

        // 2) Traer paciente y doctor usando Controllers
        paciente = pacienteCtrl.obtenerPorId(cita.getId_paciente());
        doctor = doctorCtrl.obtenerPorId(cita.getId_doctor());

        // 3) Pintar datos (solo lectura)
        txtNombrePaciente.setText(paciente != null ? paciente.getNombre() : "(No encontrado)");
        txtEdad.setText(paciente != null ? String.valueOf(paciente.getEdad()) : "");
        txtMotivoConsulta.setText(cita.getMotivo_Consulta() != null ? cita.getMotivo_Consulta() : "");

        // 4) Cargar combo de medicamentos
        cargarMedicamentosCombo();

        // 5) Limpia campos de captura
        txtTratamiento.setText("");
        txtDuracionTratamiento.setText("");
        txtIndicacionesMedicamentos.setText("");
        medsModel.setRowCount(0);
        cmbMedicamento.setSelectedIndex(-1);
    }

    private void cargarMedicamentosCombo() {
        DefaultComboBoxModel<Object> m = new DefaultComboBoxModel<>();
        for (model.Medicamento med : medicamentoCtrl.obtenerTodos()) {
            m.addElement(new ComboItem(med.getId_medicamento(), med.getNombre()));
        }
        cmbMedicamento.setModel(m);
        cmbMedicamento.setSelectedIndex(-1);
    }

    private int getSelectedMedicamentoId() {
        Object sel = cmbMedicamento.getSelectedItem();
        if (sel instanceof ComboItem it) {
            return it.id;
        }
        return -1;
    }
}
