/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author cmartinez
 */
public class frmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        pnlContent.setLayout(new java.awt.BorderLayout());
        setLocationRelativeTo(null);
        setResizable(false);
        mostrarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnPacientes = new javax.swing.JButton();
        btnDoctores = new javax.swing.JButton();
        btnAgendarCita = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnExpediente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Gratuita - Panel Principal");
        setFocusCycleRoot(false);
        setResizable(false);

        pnlRoot.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CLÍNICA GRATUITA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenido");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(154, 154, 154))))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlRoot.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setLayout(new java.awt.GridLayout(3, 2));

        btnPacientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPacientes.setText("PACIENTES");
        btnPacientes.setPreferredSize(new java.awt.Dimension(200, 80));
        btnPacientes.addActionListener(this::btnPacientesActionPerformed);
        pnlMenu.add(btnPacientes);

        btnDoctores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoctores.setText("DOCTORES");
        btnDoctores.setPreferredSize(new java.awt.Dimension(200, 80));
        btnDoctores.addActionListener(this::btnDoctoresActionPerformed);
        pnlMenu.add(btnDoctores);

        btnAgendarCita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgendarCita.setText("AGENDAR CITA");
        btnAgendarCita.setPreferredSize(new java.awt.Dimension(200, 80));
        btnAgendarCita.addActionListener(this::btnAgendarCitaActionPerformed);
        pnlMenu.add(btnAgendarCita);

        btnConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsulta.setText("INICIAR CONSULTA");
        btnConsulta.setPreferredSize(new java.awt.Dimension(200, 80));
        btnConsulta.addActionListener(this::btnConsultaActionPerformed);
        pnlMenu.add(btnConsulta);

        btnExpediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExpediente.setText("EXPEDIENTE DE PACIENTES");
        btnExpediente.setPreferredSize(new java.awt.Dimension(200, 80));
        btnExpediente.addActionListener(this::btnExpedienteActionPerformed);
        pnlMenu.add(btnExpediente);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlRoot.add(pnlContent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        // TODO add your handling code here:
        mostrarPaciente();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctoresActionPerformed
        // TODO add your handling code here:
        mostrarDoctor();
    }//GEN-LAST:event_btnDoctoresActionPerformed

    private void btnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitaActionPerformed
        // TODO add your handling code here:
        mostrarAgendarCita();
    }//GEN-LAST:event_btnAgendarCitaActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        frmSeleccionarCita dlg = new frmSeleccionarCita(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpedienteActionPerformed
        // TODO add your handling code here:
        mostrarExpediente();
    }//GEN-LAST:event_btnExpedienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarCita;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnDoctores;
    private javax.swing.JButton btnExpediente;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanel(javax.swing.JPanel panel) {
        pnlContent.removeAll();
        pnlContent.add(panel, java.awt.BorderLayout.CENTER);
        pnlContent.revalidate();
        pnlContent.repaint();
        pack();
        setLocationRelativeTo(null);
    }

    public void mostrarMenu() {
        mostrarPanel(pnlMenu);
    }

    public void mostrarPaciente() {
        mostrarPanel(new frmPaciente(this));
    }

    public void mostrarDoctor() {
        mostrarPanel(new frmDoctor(this));
    }

    public void mostrarAgendarCita() {
        mostrarPanel(new frmAgendarCita(this));
    }

    public void mostrarAtenderCita(int idCita) {
        mostrarPanel(new frmAtenderCita(this, idCita));
    }

    public void mostrarSeleccionarCita() {
        frmSeleccionarCita dlg = new frmSeleccionarCita(this);
        dlg.setVisible(true);
    }

    public void mostrarExpediente() {
        mostrarPanel(new frmExpediente(this));
    }
}
