/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.Agenda_DiariaController;
import controller.Cita_MedicaController;
import controller.DoctorController;
import controller.PacienteController;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Agenda_Diaria;

/**
 *
 * @author Afgord
 */
public class frmSeleccionarCita extends javax.swing.JDialog {

    private frmPrincipal principal;
    private final DoctorController doctorCtrl = new DoctorController();
    private final PacienteController pacienteCtrl = new PacienteController();
    private final Agenda_DiariaController agendaCtrl = new Agenda_DiariaController();
    private final Cita_MedicaController citaCtrl = new Cita_MedicaController();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSeleccionarCita.class.getName());

    /**
     * Creates new form frmSeleccionarCita
     */
    public frmSeleccionarCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        postInit();
    }

    public frmSeleccionarCita(frmPrincipal principal) {
        super(principal, true);
        this.principal = principal;
        initComponents();
        postInit(); // <- aquí configuramos todo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHEADER = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMID = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbPaciente = new javax.swing.JComboBox();
        scrollTablaCitas = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        pnlBOTTOM = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SELECCIONAR CITA");

        javax.swing.GroupLayout pnlHEADERLayout = new javax.swing.GroupLayout(pnlHEADER);
        pnlHEADER.setLayout(pnlHEADERLayout);
        pnlHEADERLayout.setHorizontalGroup(
            pnlHEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHEADERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHEADERLayout.setVerticalGroup(
            pnlHEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHEADERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("ID/Nombre de Doctor: ");

        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDoctor.addActionListener(this::cmbDoctorActionPerformed);

        jLabel3.setText("ID/Nombre de Paciente: ");

        cmbPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPaciente.addActionListener(this::cmbPacienteActionPerformed);

        javax.swing.GroupLayout pnlMIDLayout = new javax.swing.GroupLayout(pnlMID);
        pnlMID.setLayout(pnlMIDLayout);
        pnlMIDLayout.setHorizontalGroup(
            pnlMIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMIDLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMIDLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMIDLayout.setVerticalGroup(
            pnlMIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollTablaCitas.setViewportView(tblCitas);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout pnlBOTTOMLayout = new javax.swing.GroupLayout(pnlBOTTOM);
        pnlBOTTOM.setLayout(pnlBOTTOMLayout);
        pnlBOTTOMLayout.setHorizontalGroup(
            pnlBOTTOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBOTTOMLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBOTTOMLayout.setVerticalGroup(
            pnlBOTTOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBOTTOMLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        btnEliminar.setText("CANCELAR CITA");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBOTTOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollTablaCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTablaCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBOTTOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Integer idCita = getIdCitaSeleccionada();
        if (idCita == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita de la tabla.");
            return;
        }

        int op = JOptionPane.showConfirmDialog(
                this,
                "¿Cancelar la cita " + idCita + "?\n(Se marcará como 'cancelada')",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (op != JOptionPane.YES_OPTION) {
            return;
        }

        boolean ok = citaCtrl.cancelarCita(idCita); // <- el método que ya platicamos
        JOptionPane.showMessageDialog(this, citaCtrl.getUltimo_mensaje());

        if (ok) {
            cargarTablaAgendaPorDoctor(); // refresca (y ya no debe salir por la view)
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        Integer idCita = getIdCitaSeleccionada();
        System.out.println("SELECCIONAR -> idCita=" + idCita);
        if (idCita == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita de la tabla.");
            return;
        }

        boolean ok = citaCtrl.iniciarConsulta(idCita);
        JOptionPane.showMessageDialog(this, citaCtrl.getUltimo_mensaje());
        if (!ok) {
            return;
        }

        if (principal != null) {
            principal.mostrarAtenderCita(idCita);
        }

        dispose();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPacienteActionPerformed
        aplicarFiltrosYRefrescar();
    }//GEN-LAST:event_cmbPacienteActionPerformed

    private void cmbDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoctorActionPerformed
        cargarTablaAgendaPorDoctor();
    }//GEN-LAST:event_cmbDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frmSeleccionarCita dialog = new frmSeleccionarCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cmbDoctor;
    private javax.swing.JComboBox cmbPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlBOTTOM;
    private javax.swing.JPanel pnlHEADER;
    private javax.swing.JPanel pnlMID;
    private javax.swing.JScrollPane scrollTablaCitas;
    private javax.swing.JTable tblCitas;
    // End of variables declaration//GEN-END:variables

    // ======= Helpers =======
    private static class ComboItem {

        final int id;
        final String text;

        ComboItem(int id, String text) {
            this.id = id;
            this.text = text;
        }

        @Override
        public String toString() {
            return text;
        }
    }

    private DefaultTableModel tableModel;
    private List<Agenda_Diaria> cacheAgenda = new ArrayList<>();

    private void postInit() {
        // Centrar y título etc.
        setLocationRelativeTo(getParent());

        // Tabla
        tableModel = new DefaultTableModel(
                new Object[]{"ID Cita", "Hora", "Paciente", "Edad", "Motivo", "Estado"},
                0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tblCitas.setModel(tableModel);
        tblCitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // Combos editables (para permitir escribir ID/nombre)
        cmbDoctor.setEditable(true);
        cmbPaciente.setEditable(true);

        // Cargar datos
        cargarDoctores();
        cargarPacientes();

        // Eventos extra: filtrar al teclear en paciente
        hookFiltroPaciente();

        // De inicio, sin doctor seleccionado (tabla vacía)
        limpiarTabla();
    }

    private void cargarDoctores() {
        DefaultComboBoxModel<Object> m = new DefaultComboBoxModel<>();

        for (model.Doctor d : doctorCtrl.obtenerTodos()) {
            m.addElement(new ComboItem(d.getId_doctor(), d.getId_doctor() + " - " + d.getNombre()));
        }

        cmbDoctor.setModel(m);
        cmbDoctor.setSelectedIndex(-1);
    }

    private void cargarPacientes() {
        DefaultComboBoxModel<Object> m = new DefaultComboBoxModel<>();

        for (model.Paciente p : pacienteCtrl.obtenerTodos()) {
            m.addElement(new ComboItem(p.getId_paciente(), p.getId_paciente() + " - " + p.getNombre()));
        }

        cmbPaciente.setModel(m);
        cmbPaciente.setSelectedIndex(-1);

    }

    private int getSelectedId(javax.swing.JComboBox<?> combo) {
        Object sel = combo.getSelectedItem();
        if (sel instanceof ComboItem it) {
            return it.id;
        }

        if (sel != null) {
            String s = sel.toString().trim();
            try {
                String num = s.split("\\s|-", 2)[0].trim();
                return Integer.parseInt(num);
            } catch (Exception ignore) {
            }
        }
        return -1;
    }

    private void limpiarTabla() {
        tableModel.setRowCount(0);
    }

    private void cargarTablaAgendaPorDoctor() {
        int idDoctor = getSelectedId(cmbDoctor);
        if (idDoctor <= 0) {
            cacheAgenda = List.of();
            limpiarTabla();
            return;
        }

        cacheAgenda = agendaCtrl.obtenerAgendaParaSeleccion(idDoctor);
        aplicarFiltrosYRefrescar();

        if (cacheAgenda.isEmpty()) {
            JOptionPane.showMessageDialog(this, agendaCtrl.getUltimo_mensaje());
        }
    }

    private void aplicarFiltrosYRefrescar() {
        String filtro = "";
        Object selPac = cmbPaciente.getSelectedItem();
        if (selPac != null) {
            filtro = selPac.toString().trim().toLowerCase();
        }

        // si el usuario escribió "12 - Juan", quédate con "juan" para filtrar por nombre
        String filtroNombre = filtro;
        if (filtro.contains("-")) {
            filtroNombre = filtro.substring(filtro.indexOf("-") + 1).trim();
        }
        // si escribió solo número, también lo dejamos (para filtrar por id_cita)
        boolean filtroEsNumero = filtro.matches("^\\d+$");

        limpiarTabla();

        for (Agenda_Diaria a : cacheAgenda) {
            if (!filtro.isEmpty()) {
                String pac = a.getPaciente() != null ? a.getPaciente().toLowerCase() : "";
                String idCita = String.valueOf(a.getId_cita());

                boolean matchNombre = !filtroNombre.isEmpty() && pac.contains(filtroNombre);
                boolean matchIdCita = filtroEsNumero && idCita.contains(filtro);

                if (!(matchNombre || matchIdCita)) {
                    continue;
                }
            }

            tableModel.addRow(new Object[]{
                a.getId_cita(),
                a.getHora(),
                a.getPaciente(),
                a.getEdad(),
                a.getMotivo_consulta(),
                a.getEstado()
            });
        }
    }

    private Integer getIdCitaSeleccionada() {
        int row = tblCitas.getSelectedRow();
        if (row < 0) {
            return null;
        }

        Object v = tblCitas.getValueAt(row, 0);
        if (v == null) {
            return null;
        }

        try {
            return Integer.parseInt(v.toString().trim());
        } catch (Exception e) {
            return null;
        }
    }

    private void hookFiltroPaciente() {
        Component editor = cmbPaciente.getEditor().getEditorComponent();
        if (editor instanceof javax.swing.JTextField tf) {
            tf.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    aplicarFiltrosYRefrescar();
                }
            });
        }
    }
}
